version: '2'

services:
  haproxy:
    container_name: metfrag_haproxy
    build:
      context: ./metfrag-haproxy
      dockerfile: Dockerfile
    networks:
    - metfrag_net
    volumes:
    - ./metfrag-haproxy:/haproxy-override
    links:
    - metfrag
    ports:
    - "9003:80"
    - "9004:70"
    expose:
    - "80"
    - "70"

  metfrag:
    image: korseby/metfrag
    networks:
    - metfrag_net
    volumes:
    - $PWD/settings.properties:/usr/src/MetFragRelaunched/MetFragWeb/src/main/webapp/resources/settings.properties
    expose:
    - 8080

networks:
  metfrag_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.80.80.0/24
        ip_range: 10.80.80.0/24
        gateway: 10.80.80.1
