apiVersion: v1
kind: Service
metadata:
  name: metfrag-service
  labels:
    app: metfrag
spec:
  selector:
    app: metfrag
  type: NodePort
  ports:
  - port: 9080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: ClientIP
  #CookieStickySession: SERVERID
  clusterIP: 10.0.0.101
  #loadBalancerIP: 192.168.0.175
  externalIPs: [ "192.168.0.175" ]
  type: LoadBalancer

