apiVersion: v1
kind: ReplicationController
metadata:
  name: metfrag-rc
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: metfrag
    spec:
      containers:
      - name: metfrag
        image: korseby/metfrag
        volumeMounts:
          - name: metfrag-settings
            mountPath: "/usr/src/MetFragRelaunched/MetFragWeb/src/main/webapp/resources/settings.properties"
            readOnly: false
        ports:
        - containerPort: 8080
      volumes:
        - name: metfrag-settings
          hostPath:
            path: "/vol/phenomenal/github-korseby/docker-metfrag/settings.properties"

